# Generated by Django 4.0.5 on 2022-06-24 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scorestore', '0003_alter_goods_options_alter_userprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
